smsc:
  auth:
    system-id: stct
    password: stct1234
  ports: 64567,64568,64569
  server:
    port: 10001
    max-connection-size: 10
    non-blocking-sockets-enabled: true
    default-request-expiry-timeout: 30000
    default-window-monitor-interval: 15000
    default-window-size: 100
    default-window-wait-timeout: 30000
    default-session-counters-enabled: true
    jmx-enabled: true
  rate-sender:
    segments: 2
    dest-address-digits: "1111"
    pool-size: 0
  delivery-sender:
    worker-count: 4
  delivery-receipt:
    min-delay-ms: 500
    random-delta-ms: 100

spring:
  jmx:
    enabled: true
  profiles:
    active: prod

logging:
  level:
    root: INFO
    com.smpp.smscsim: DEBUG
    org.springframework: WARN
